name: API Triggered Build
on:
  repository_dispatch:
    types: [build-app]
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Show trigger info
      run: |
        echo "🚀 API Triggered Build"
        echo "Event: ${{ github.event_name }}"

        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "Repository Dispatch Event:"
          echo "  Type: ${{ github.event.action }}"
          echo "  Tenant: ${{ github.event.client_payload.tenant }}"
          echo "  Platform: ${{ github.event.client_payload.platform }}"
          echo "  Triggered by: ${{ github.event.client_payload.triggered_by }}"
        else
          echo "Manual Dispatch Event:"
          echo "  Tenant: ${{ github.event.inputs.tenant }}"
        fi

    - name: Validate tenant
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          TENANT="${{ github.event.client_payload.tenant }}"
        else
          TENANT="${{ github.event.inputs.tenant }}"
        fi

        echo "Validating tenant: $TENANT"

        if [ -f "env/.env.${TENANT}" ]; then
          echo "✅ Found configuration for $TENANT"
          echo "Preview:"
          head -3 "env/.env.${TENANT}"
        else
          echo "❌ No configuration found for $TENANT"
          echo "Available:"
          ls env/.env.* | head -3
        fi