name: Manual Build Test
on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant'
        required: true
        default: 'dev'

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show info
      run: |
        echo "Branch: ${{ github.ref_name }}"
        echo "Tenant: ${{ github.event.inputs.tenant }}"
        echo "Workflow is working!"