name: Manual Build Test
on:
  workflow_dispatch:
  push:
    branches: [steble_design]
    paths: ['.github/workflows/manual-build.yml']

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show info
      run: |
        echo "Branch: ${{ github.ref_name }}"
        echo "Manual Build Test is working!"